AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FormBridge backend - SAM template (Globals-based CORS, runtime python3.11)

Globals:
  Api:
    Cors:
      # exact origin (must be a quoted string inside single-quotes)
      AllowOrigin: "'https://omdeshpande09012005.github.io'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods: "'POST,OPTIONS'"
  Function:
    Timeout: 30
    Runtime: python3.11
    MemorySize: 256

Parameters:
  DDBTableName:
    Type: String
    Default: contact-form-submissions
  SesSender:
    Type: String
    Description: "Verified SES sender email address"
    Default: "noreply@formbridge.example.com"
  SesRecipients:
    Type: String
    Description: "Comma-separated list of recipient email addresses"
    Default: "admin@formbridge.example.com"
  FrontendOrigin:
    Type: String
    Description: "Allowed frontend origin for CORS"
    Default: "https://omdeshpande09012005.github.io"

Resources:

  # Explicit API resource (Cors configured via Globals above)
  FormApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  ContactTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DDBTableName
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      # TODO: Add GSI for analytics queries (e.g., by form_id or timestamp)

  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: contactFormProcessor
      Handler: contact_form_lambda.lambda_handler
      CodeUri: .
      Environment:
        Variables:
          DDB_TABLE: !Ref DDBTableName
          SES_SENDER: !Ref SesSender
          SES_RECIPIENTS: !Ref SesRecipients
          FRONTEND_ORIGIN: !Ref FrontendOrigin
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:Query
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DDBTableName}
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      Events:
        ContactApi:
          Type: Api
          Properties:
            RestApiId: !Ref FormApi
            Path: /submit
            Method: post
        # TODO: Add /analytics endpoint for retrieving and aggregating submissions

Outputs:
  ApiUrl:
    Description: "API Gateway invoke URL for the submit endpoint"
    Value: !Sub "https://${FormApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/submit"
