name: CI - build & test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Install SAM CLI & pip deps
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli
          # install backend requirements (if present)
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      - name: Run tests (none by default)
        run: |
          echo "No tests configured. Add pytest and tests/ if you want unit tests."
          # Example (uncomment when you add tests):
          # pip install pytest
          # pytest -q

      - name: Build SAM application
        working-directory: backend
        run: |
          sam build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sam-built-artifacts
          path: backend/.aws-sam/build
