name: CI - build & test & deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Install SAM CLI & pip deps
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli
          # install backend requirements (if present)
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      - name: Build SAM application (non-containerized)
        working-directory: backend
        run: |
          # Build on the runner (we've installed python 3.11) - avoid --use-container to prevent missing runtime inside docker
          sam build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sam-built-artifacts
          path: backend/.aws-sam/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install AWS SAM CLI
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS (SAM)
        working-directory: backend
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Use non-guided deploy. Do NOT pass --resolve-s3 if you have configured s3 bucket in samconfig or environment,
          # passing both --s3-bucket and --resolve-s3 can cause failures.
          sam deploy --stack-name formbridge-stack \
                     --capabilities CAPABILITY_IAM \
                     --no-confirm-changeset \
                     --no-fail-on-empty-changeset
