name: CI - build & test & deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Install SAM CLI & pip deps
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli
          # install backend requirements (if present)
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      - name: Build SAM application (containerized)
        working-directory: backend
        run: |
          # build with container to match runtime precisely
          sam build --use-container

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sam-built-artifacts
          path: backend/.aws-sam/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install AWS SAM CLI
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli

      - name: Deploy to AWS
        working-directory: backend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          sam deploy --stack-name formbridge-stack \
                     --resolve-s3 \
                     --capabilities CAPABILITY_IAM \
                     --no-confirm-changeset \
                     --no-fail-on-empty-changeset
